"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var GameLoop_1 = require("./gameloop/GameLoop");
exports.GameLoop = GameLoop_1.GameLoop;
var FpsReport_1 = require("./gameloop/FpsReport");
exports.FPSReport = FpsReport_1.FPSReport;
var GameLoopEventRegister_1 = require("./gameevent/GameLoopEventRegister");
exports.GameLoopEventRegister = GameLoopEventRegister_1.GameLoopEventRegister;
var GameEventRegister_1 = require("./gameevent/GameEventRegister");
exports.GameEventRegister = GameEventRegister_1.GameEventRegister;
var SaveHandler_1 = require("./gamesave/SaveHandler");
exports.SaveHandler = SaveHandler_1.SaveHandler;
